/*******************************************************************************
  Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This file contains the "main" function for a project.

  Description:
    This file contains the "main" function for a project.  The
    "main" function calls the "SYS_Initialize" function to initialize the state
    machines of all modules in the system
 *******************************************************************************/

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************

#include <stddef.h>                     // Defines NULL
#include <stdbool.h>                    // Defines true
#include <stdlib.h>                     // Defines EXIT_FAILURE
#include "definitions.h"                // SYS function prototypes

// *****************************************************************************
// *****************************************************************************
// Section : Parameters and variables
// *****************************************************************************
// *****************************************************************************
/////////////////////////////// PROGRAM VARIABLES ///////////////////////////// 
volatile uint32_t PB_Counter = 0;        
//This counter is incremented each time PB0 pushbutton is pressed and 
//decremented each time PB1 pushbutton is pressed// 

// *****************************************************************************
// *****************************************************************************
// Section : Local Functions
// *****************************************************************************
// *****************************************************************************
//////////////////////////////// Timeout_Handler ///////////////////////////////
// This function is called at each interrupt generated by the systick timer.
// It toggles the LED corresponding to the PB_Counter value.
void Timeout_Handler (uintptr_t context) // function handling the Systick Timer interrupt
{
    switch (PB_Counter) // Only one LED out of the 6 blinks at a time. The LED selection depends on the PB_Counter
    {
        case 0:
            LED0_Toggle();
            break;
        case 1:
            LED1_Toggle();
            break;
        case 2:
            LED2_Toggle();
            break;    
        case 3:
            LED3_Toggle();
            break;
        case 4:
            LED4_Toggle();
            break;   
        case 5:
            LED5_Toggle();
            break;    
    }
}

//////////////////////////////// LEDS_Clear //////////////////////////////////
// This function enables to swith off all the LEDS each time PB0 and PB1 are pressed.
// It allows to jump from one LED to another one from a clean state.
// The LEDs are off when the associated I/O port is at low state (Cleared)

void LEDS_Clear (void)
{
    LED0_Off();
    LED1_Off();
    LED2_Off();
    LED3_Off();
    LED4_Off();
    LED5_Off();
}

// *****************************************************************************
// *****************************************************************************
// Section: Main Entry Point
// *****************************************************************************
// *****************************************************************************

int main ( void )
{
    /* Initialize all modules */
    SYS_Initialize ( NULL );
    
    SYSTICK_TimerCallbackSet(&Timeout_Handler,(uintptr_t) NULL);
    // Systick Interrupt Handler
    SYSTICK_TimerStart(); // System timer control
    
    LEDS_Clear();
    printf("*** Getting Started with SAMRH707F18 microcontroller ***\n\r");
    printf("LED%ld is blinking ...\n\r",PB_Counter);

    while ( true )
    {
        if (PB0_Get()==0) { //Test if PB0 pushbutton is pressed 
            while(PB0_Get()==0){}; //and released
            if (PB_Counter==5) PB_Counter=0; //Test if the counter must be reset
            else PB_Counter++;               //when the rightmost LED is reached.
            LEDS_Clear();
            printf("LED%ld is blinking ...\n\r",PB_Counter);
        }
            if (PB1_Get()==0) { //Test if PB1 pushbutton is pressed 
            while(PB1_Get()==0){}; //and released
            if (PB_Counter==0) PB_Counter=5; //Test if the counter must be reset
            else PB_Counter--;               //when the leftmost LED is reached.
            LEDS_Clear();
            printf("LED%ld is blinking ...\n\r",PB_Counter);
        }
        
        
        /* Maintain state machines of all polled MPLAB Harmony modules. */
        SYS_Tasks ( );
    }

    /* Execution should not come here during normal operation */

    return ( EXIT_FAILURE );
}


/*******************************************************************************
 End of File
*/

